# SPDX-FileCopyrightText: 2024 PNED G.I.E.
#
# SPDX-License-Identifier: Apache-2.0

version: "3"

services:
  frontend:
    build:
      context: .
    restart: unless-stopped
    environment:
      - CKAN_URL=https://ckan-test.healthdata.nl
      - IDENTITY_SERVER_HOST_URL=https://keycloak-test.healthdata.nl
      - IDENTITY_SERVER_URL=https://keycloak-test.healthdata.nl/realms/ckan
      - IDENTITY_SERVER_CLIENT_ID=ckan
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
    ports:
      - "80:80"
    extra_hosts:
      - "catalogue.local.onemilliongenomes.eu:host-gateway"
      - "id.local.onemilliongenomes.eu:host-gateway"
