# SPDX-FileCopyrightText: 2024 PNED G.I.E.
#
# SPDX-License-Identifier: Apache-2.0
version: "3"

services:
  frontend:
    build:
      context: .
    restart: unless-stopped
    environment:
      - CKAN_URL=https://ckan-test.healthdata.nl
      - IDENTITY_SERVER_HOST_URL=https://keycloak-test.healthdata.nl
      - IDENTITY_SERVER_URL=https://keycloak-test.healthdata.nl/realms/ckan
      - IDENTITY_SERVER_CLIENT_ID=ckan
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "-qO",
          "-",
          "http://localhost:3000/api/health",
          "||",
          "exit",
          "1",
        ]
    ports:
      - "80:3000"
