version: "3"

services:
  frontend:
    build: 
      context: .
    restart: unless-stopped
    environment:
      - BACKEND_URL=http://catalogue.local.gdi.lu
      - IDENTITY_SERVER_URL=http://id.local.gdi.lu
      - IDENTITY_SERVER_CLIENT_ID=ckan
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
    ports:
      - "80:80"
    extra_hosts:
      - "catalogue.local.gdi.lu:host-gateway"
      - "id.local.gdi.lu:host-gateway"
