# SPDX-FileCopyrightText: 2024 PNED G.I.E.
# SPDX-FileContributor: Stichting Health-RI
#
# SPDX-License-Identifier: Apache-2.0

name: Publish Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Increment (major, minor, patch)'
        required: true
        default: 'patch'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/genomicdatainfrastructure/gdi-userportal-frontend
  DOCKER_METADATA_OUTPUT_TAGS:
  REPOSITORY_URL: ${{ github.server_url }}/${{ github.repository }}
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF_NAME: ${{ github.ref_name }}
  BUILD_DATE: ""

jobs:
  ort:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oss-review-toolkit/ort-ci-github-action@v1
        with:
          allow-dynamic-versions: "true"
          fail-on: "issues"
          run: "cache-dependencies,cache-scan-results,labels,analyzer,evaluator,advisor,reporter,upload-results"

  versioning:
    runs-on: ubuntu-latest
    needs: ort
    outputs:
      new_tag: ${{ steps.tagging.outputs.new_tag }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Git User Identity
        run: |
          git config --local user.email "github-actions@users.noreply.github.com"
          git config --local user.name "GitHub Actions"

      - name: Fetch Latest Tag and Increment Version
        id: tagging
        run: |
          LATEST_TAG=$(git tag --sort=-creatordate | head -n 1)
          echo "Latest tag: $LATEST_TAG"

          # Extract Major, Minor, Patch
          IFS='.' read -r MAJOR MINOR PATCH <<<"${LATEST_TAG//v/}"
          INCREMENT=${{ github.event.inputs.version }}
          echo "Updating : $INCREMENT version"

          case "$INCREMENT" in
            major) ((MAJOR++)); MINOR=0; PATCH=0 ;;
            minor) ((MINOR++)); PATCH=0 ;;
            patch|*) ((PATCH++)) ;;
          esac

          NEW_TAG="v$MAJOR.$MINOR.$PATCH"
          echo "Pushing this tag: $NEW_TAG"

          git tag -a "$NEW_TAG" -m "Release $NEW_TAG"
          git push origin "$NEW_TAG"

          echo "New tag pushed: $NEW_TAG"
          echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT

      - name: Set execute permissions for changelog script
        run: chmod +x changelog.sh

      - name: Update CHANGELOG.md
        run: ./changelog.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  publish-release:
    runs-on: ubuntu-latest
    needs: versioning
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Generate and Publish GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          LATEST_TAG="${{ needs.versioning.outputs.new_tag }}"
          PREVIOUS_TAG=$(git tag --sort=-creatordate | sed -n '2p')

          echo "Creating GitHub release for $LATEST_TAG from previous release $PREVIOUS_TAG"

          gh release create "$LATEST_TAG" \
            --title "Release $LATEST_TAG" \
            --generate-notes \
            --notes-start-tag "$PREVIOUS_TAG"

  publish-docker-image:
    runs-on: ubuntu-latest
    needs: publish-release
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set BUILD_DATE
        run: echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=schedule,priority=400
            type=ref,event=branch,priority=600
            type=ref,event=pr,priority=500
            type=semver,pattern={{version}},priority=700
            type=semver,pattern={{major}}.{{minor}},priority=900
            type=semver,pattern={{major}},priority=800
            type=sha,priority=1000
          labels: |
            vcs-ref=${{env.GITHUB_SHA}}
            build-date=${{env.BUILD_DATE}}
            org.opencontainers.image.created=${{env.BUILD_DATE}}
            release=${{env.BUILD_DATE}}
            version=${{env.GITHUB_REF_NAME}}
            org.opencontainers.image.version=${{env.GITHUB_REF_NAME}}
            org.opencontainers.image.url=${{env.REPOSITORY_URL}}
            org.opencontainers.image.source=${{env.REPOSITORY_URL}}
            org.opencontainers.image.documentation=${{env.REPOSITORY_URL}}
            help=${{env.REPOSITORY_URL}}
            url=${{env.REPOSITORY_URL}}
            name=${{env.IMAGE_NAME}}

      - name: Extract last tag
        id: tag
        run: |
          IFS=',' read -ra TAGS <<< "${{ steps.meta.outputs.tags }}"
          LAST_INDEX=$((${#TAGS[@]} - 1))
          echo "last_tag=${TAGS[LAST_INDEX]}" >> $GITHUB_OUTPUT

      - name: Build Docker image for scanning
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          load: true
          tags: ${{ steps.tag.outputs.last_tag }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@0.29.0
        with:
          image-ref: "${{ steps.tag.outputs.last_tag }}"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
        env:
          TRIVY_SKIP_DB_UPDATE: true
          TRIVY_SKIP_JAVA_DB_UPDATE: true

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
