# SPDX-FileCopyrightText: 2024 PNED G.I.E.
# SPDX-License-Identifier: Apache-2.0

name: Weekly Security Check

on:
  schedule:
    - cron: "0 13 * * 1" # It will work at 13:00 on every Monday
  workflow_dispatch:

jobs:
  ort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oss-review-toolkit/ort-ci-github-action@7f23c1f8d169dad430e41df223d3b8409c7a156e
        with:
          allow-dynamic-versions: "true"
          fail-on: "issues"
          run: "cache-dependencies,cache-scan-results,labels,analyzer,evaluator,advisor,reporter,upload-results"

  trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Find Docker images
        id: docker-images
        run: |
          echo "::set-output name=images::$(docker images --format '{{.Repository}}:{{.Tag}}')"

      - name: Run Trivy vulnerability scanner on each Docker image
        run: |
          for image in ${{ steps.docker-images.outputs.images }}
          do
            echo "Scanning image: $image"
            docker pull $image
            trivy image --format template --template "@contrib/sarif.tpl" --exit-code 1 --ignore-unfixed --vuln-type os,library --severity CRITICAL,HIGH $image > trivy-results.sarif
          done

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
        sarif_file: "trivy-results.sarif"
